---
title: "manhar"
author: "me"
date: "2/27/2021"
output: html_document
---

```{r}
getwd()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(janitor)
library(here)
library(naniar)
library(skimr)
```

```{r}
library("shiny")
library("shinydashboard")
```

```{r}
options(scipen = 999)
```


```{r}
covid <- read.csv("Data/WHO-COVID-19-global-data.csv")
```

```{r}
covid<-janitor::clean_names(covid)
```

```{r}
glimpse(covid)
```

```{r}
#covid%>%
#  str_replace_all(i_date_reported, "/", "-")
```


```{r}
names(covid)
```



```{r}
lapply(covid, class)
```


```{r}
#covid$i_date_reported <- as.factor(covid$i_date_reported)
```

```{r}
glimpse(covid)
```




```{r, eval=F, echo=T}
ui <- dashboardPage(
  dashboardHeader(title = "Covid-19"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("x", "Select X Variable", choices = c("i_date_reported", "new_cases", "cumulative_cases", "new_deaths", "cumulative_deaths"), selected = "i_date_reported"),
  selectInput("y", "Select Y Variable", choices = c("i_date_reported", "new_cases", "cumulative_cases", "new_deaths", "cumulative_deaths"), selected = "cumulative_cases"),
   sliderInput("pointsize", "Select the Point Size", min = 1, max = 5, value = 2, step = 0.5)
  ),
  box(title = "Plot of Covid-19 cases and deaths", width = 7,
  plotOutput("plot", width = "600px", height = "500px")
  )
  )
  )
)

server <- function(input, output, session) { 
  output$plot <- renderPlot({
    ggplot(covid, aes_string(x = input$x, y = input$y)) + geom_point(size=input$pointsize, alpha=0.8) + theme_light(base_size = 18)
  })
  session$onSessionEnded(stopApp)
  }

shinyApp(ui, server)
```



```{r}
#install.packages("lubridate")
```

```{r}
covid%>%
  filter(i_date_reported == "1/3/2020" | i_date_reported == "7/7/2020")%>%
  ggplot(aes(x=i_date_reported, y=new_cases)) + geom_point()
  
```

https://shiny.rstudio.com/articles/shiny-server.html

http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels

```{r}
covid%>%
  filter(i_date_reported=="2/19/2020")%>%
  select(country)
```


```{r, eval=F, echo=T}
ui <- dashboardPage(
  dashboardHeader(title = "Covid-19"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("x", "Select X Variable", choices = c("i_date_reported", "new_cases", "cumulative_cases", "new_deaths", "cumulative_deaths"), selected = "i_date_reported"),
  selectInput("y", "Select Y Variable", choices = c("i_date_reported", "new_cases", "cumulative_cases", "new_deaths", "cumulative_deaths"), selected = "cumulative_cases"),
   selectInput("z", "Select Country", choices = c("Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia (Plurinational State of)", "Bonaire", "Bosnia and Herzegovina", "Botswana", "British Virgin Islands", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Colombia","Comoros","Congo"	"Cook Islands", "Costa Rica", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czechia","Democratic People's Republic of Korea", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic","Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala","Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo[1]", "Kuwait"	, "Kyrgyzstan", "Lao People's Democratic Republic"	, "Latvia", "Lebanon", "Lesotho", "Liberia"	, "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia (Federated States of)", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "North Macedonia", "Northern Mariana Islands (Commonwealth of the)", "Norway", "Oman", "Other", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines"	, "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Republic of Korea", "Republic of Moldova", "Romania", "Russian Federation"	, "Rwanda", "Saba", "Saint Barthélemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin", "Saint Pierre and Miquelon"	, "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Eustatius", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syrian Arab Republic", "Tajikistan", "Thailand", "The United Kingdom", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Republic of Tanzania", "United States of America", "United States Virgin Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela (Bolivarian Republic of)", "Viet Nam", "Wallis and Futuna", "Yemen", "Zambia", "Zimbabwe"), selected = "United States of America"),
   sliderInput("pointsize", "Select the Point Size", min = 1, max = 5, value = 2, step = 0.5)
  ),
  box(title = "Plot of Covid-19 cases and deaths", width = 7,
  plotOutput("plot", width = "600px", height = "500px")
  )
  )
  )
)


server <- function(input, output, session) { 
  output$plot <- renderPlot({
    covid%>%
  filter(i_date_reported==input$x & new_cases==input$y & country==input$z)%>%
  ggplot(covid, aes_string(x = input$x, y = input$y, z=input$z)) + geom_point(size=input$pointsize, alpha=0.8) + theme_light(base_size = 18)
  })
  session$onSessionEnded(stopApp)
  }

shinyApp(ui, server)
```




```{r}
#UC_admit %>% 
#      filter(Ethnicity==input$x & Campus==input$y & Category==input$z) %>% #
#      ggplot(aes(x=Academic_Yr, y=FilteredCountFR, fill=FilteredCountFR))
```

```{r}
covid$i_date_reported <- as.Date(covid$i_date_reported, format = "%m/%d/%Y")
```


```{r}
covid$i_date_reported <- as.Date(covid$i_date_reported)
covid$cumulative_cases <- as.numeric(covid$cumulative_cases)
covid$country<- as.factor(covid$country)
```

```{r}
glimpse(covid)
```


```{r, eval=F, echo=T}
ui <- dashboardPage(
  dashboardHeader(title = "Covid-19"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("x", "Select X Variable", choices = c("i_date_reported", "new_cases", "cumulative_cases", "new_deaths", "cumulative_deaths"), selected = "i_date_reported"),
  selectInput("y", "Select Y Variable", choices = c("i_date_reported", "new_cases", "cumulative_cases", "new_deaths", "cumulative_deaths"), selected = "cumulative_cases"),
   selectInput("z", "Select Country", choices = c("Costa Rica", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czechia","Democratic People's Republic of Korea", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic","Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "Gabon", "Gambia", "Georgia", "Germany", "United States of America"), selected = "United States of America"),
   sliderInput("pointsize", "Select the Point Size", min = 1, max = 5, value = 2, step = 0.5)
  ),
  box(title = "Plot of Covid-19 cases and deaths", width = 7,
  plotOutput("plot", width = "600px", height = "500px")
  )
  )
  )
)


server <- function(input, output, session) { 
  output$plot <- renderPlot({
    covid%>%
  filter(i_date_reported==input$x & new_cases==input$y & country==input$z)%>%
  ggplot(aes(x = input$x, y = input$y)) + geom_point(size=input$pointsize, alpha=0.8) + theme_light(base_size = 18)
  })
  session$onSessionEnded(stopApp)
  }

shinyApp(ui, server)
```
```{r}
covid%>%
  filter(country=="United States of America")
```


